package net.pincette.mongo;

import java.util.Map;
import java.util.function.BiFunction;
import javax.json.JsonObject;
import javax.json.JsonValue;

/**
 * The implementation generated by a MongoDB operator. It will receive two arguments: the JSON
 * object to work on and variables, which have names that start with <code>$$</code>.
 *
 * @author Werner Donné
 * @since 1.3
 */
public interface Implementation extends BiFunction<JsonObject, Map<String, JsonValue>, JsonValue> {}
