package net.pincette.mongo;

import java.util.Map;
import java.util.Optional;
import java.util.function.BiFunction;
import javax.json.JsonObject;
import javax.json.JsonValue;

/**
 * The implementation generated by a MongoDB operator. It will receive two arguments: the JSON
 * object to work on and variables, which have names that start with <code>$$</code>. Through the
 * optional result, an implementation can impose extra conditions.
 *
 * @author Werner Donné
 * @since 4.3.0
 */
public interface ImplementationOptional
    extends BiFunction<JsonObject, Map<String, JsonValue>, Optional<JsonValue>> {}
